---
# Copy the necessary website code to the nodes

 - name: copy-apache-code
   copy:
     src: files/apache_index.html
     dest: /var/www/html/index.html
     mode: 0644
   when: group_names[0] == "apacheservers"
   notify: send-message-apache

 - name: copy-nginx-code
   copy:
     src: files/nginx_index.html
     dest: /var/www/html/index.html
     mode: 0644
   when: group_names[0] == "nginxservers"
   notify: send-message-nginx
