kind: Deployment
apiVersion: apps/v1
metadata:
  name: persistent-volume-pod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: persistent-volumes-app
  template:
    metadata:
      labels:
        app: persistent-volumes-app
    spec:
      containers:
      - name: persistent-volume-container
        image: nginx:latest
        ports:
        - containerPort: 80
        env:
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: password
        volumeMounts:
        - name: nfs-pvc
          mountPath: "/mnt"
      tolerations:
      - key: "persistent-volumes"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      volumes:
      - name: nfs-pvc
        persistentVolumeClaim:
          claimName: persistent-volume-claim
