apiVersion: v1
kind: Service
metadata:
  name: persistent-volume-service
spec:
  selector:
    app: persistent-volumes-app
  type: NodePort
  ports:
  - name: http
    port: 8080
    targetPort: 80
    nodePort: 32000
    protocol: TCP
