apiVersion: apps/v1
kind: Deployment
metadata:
  name: module8-kubernetes1-assignment-pod1-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pod1
  template:
    metadata:
      labels:
        app: pod1
    spec:
      containers:
      - name: pod1-container
        image: cliffordanup/module8-kubernetes1-assignment:pod1
        ports:
        - containerPort: 80
