apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-grafana-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: prometheus-grafana-app
  template:
    metadata:
      labels:
        app: prometheus-grafana-app
    spec:
      containers:
      - name: prometheus-grafana-container
        image: nginx:latest
        ports:
        - containerPort: 80
