apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: monitoring
spec:
  selector:
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: kube-prometheus
    prometheus: k8s
  type: NodePort
  ports:
  - name: http
    port: 8082
    targetPort: 9090
    nodePort: 30001
    protocol: TCP
