apiVersion: v1
kind: Service
metadata:
  name: prometheus-grafana-service
spec:
  selector:
    app: prometheus-grafana-app
  type: NodePort
  ports:
  - name: http
    port: 8088
    targetPort: 80
    nodePort: 32001
    protocol: TCP
