apiVersion: apps/v1
kind: Deployment
metadata:
  name: module8-kubernetes1-assignment-pod2-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pod2
  template:
    metadata:
      labels:
        app: pod2
    spec:
      containers:
      - name: pod2-container
        image: cliffordanup/module8-kubernetes1-assignment:pod2
        ports:
        - containerPort: 80
